### PR TITLE
Complete the c++ code generation portions of the master installer compiler

### PR DESCRIPTION
**Pull request by jasonleenaylor**
[Review on Reviewable](https://reviewable.io/reviews/sillsdev/masterinstaller/6)

### CODE REVIEW

**Comment by papeh** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[Code and Projects/ConfigDisks.cpp.template, line 4 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-K85iOZ_qc1vO9zqzmW7:-K85iOZ_qc1vO9zqzmW8:-65037959) ([raw file](https://github.com/sillsdev/masterinstaller/blob/e785a026ed66ed1983cb8310d1d0da03e449b446/Code and Projects/ConfigDisks.cpp.template#L4)):_
is it possible to get rid of this trailing whitespace? I think it's affecting the diff

---

_[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 31 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-K85qxiZ8UrtlIM2uyE0:-K85qxiZ8UrtlIM2uyE1:1899103219) ([raw file](https://github.com/sillsdev/masterinstaller/blob/e785a026ed66ed1983cb8310d1d0da03e449b446/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L31)):_
I would prefer these three functions be implemented in the same order in which they are called

---

_[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 86 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-K85oaforsgnFhFxC_1b:-K85oafpo9wTK2p9CPvj:-306546560) ([raw file](https://github.com/sillsdev/masterinstaller/blob/e785a026ed66ed1983cb8310d1d0da03e449b446/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L86)):_
I'm not sure these comments about history will be useful to future developers. Perhaps they should be left out.

---

_[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 86 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-K85pIJgPijkW_H84IRA:-K85pIJgPijkW_H84IRB:786909401) ([raw file](https://github.com/sillsdev/masterinstaller/blob/e785a026ed66ed1983cb8310d1d0da03e449b446/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L86)):_
Should this use IsNullOrEmpty?

---

_[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 98 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-K85pPjKc-yu4_OrU2c5:-K85pPjKc-yu4_OrU2c6:1737605547) ([raw file](https://github.com/sillsdev/masterinstaller/blob/e785a026ed66ed1983cb8310d1d0da03e449b446/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L98)):_
IsNullOrEmpty?

---

_[Code and Projects/MasterInstallerConfiguratorTests/MasterInstallerConfiguratorTests/ConfigurationModelTests.cs, line 228 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-K85n_fbIAGQuU7xKlXd:-K85n_fbIAGQuU7xKlXe:1223273048) ([raw file](https://github.com/sillsdev/masterinstaller/blob/e785a026ed66ed1983cb8310d1d0da03e449b446/Code and Projects/MasterInstallerConfiguratorTests/MasterInstallerConfiguratorTests/ConfigurationModelTests.cs#L228)):_
Did you mean to use this variable in the Assert below? Otherwise, why not simply hard-code 'true' into the basicModelXmlString

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6)_

**Comment by jasonleenaylor** [comment]
Review status: 7 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

_[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 86 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-K85oaforsgnFhFxC_1b:-KC2krWCOEqu5iOy1E1v:-952560795) ([raw file](https://github.com/sillsdev/masterinstaller/blob/e785a026ed66ed1983cb8310d1d0da03e449b446/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L86)):_
This is probably true, but they were documentation for me in the intermediate process. I think I'll remove them later to keep the documentation in the history.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6)_

**Comment by jasonleenaylor** [comment]
Review status: 7 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

_[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 86 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-K85pIJgPijkW_H84IRA:-KCH5acfQ97pA9Ca0oE-:1468734316) ([raw file](https://github.com/sillsdev/masterinstaller/blob/e785a026ed66ed1983cb8310d1d0da03e449b446/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L86)):_
Not a string.

---

_[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 98 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-K85pPjKc-yu4_OrU2c5:-KCH5X4Y0Ier_jbqag_7:1468734316) ([raw file](https://github.com/sillsdev/masterinstaller/blob/e785a026ed66ed1983cb8310d1d0da03e449b446/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L98)):_
Not a string.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6)_

**Comment by jasonleenaylor** [comment]
Review status: 7 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

_[Code and Projects/MasterInstallerConfiguratorTests/MasterInstallerConfiguratorTests/ConfigurationModelTests.cs, line 228 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-K85n_fbIAGQuU7xKlXd:-KCMq2IrVDhitkE_I1ov:-499146009) ([raw file](https://github.com/sillsdev/masterinstaller/blob/e785a026ed66ed1983cb8310d1d0da03e449b446/Code and Projects/MasterInstallerConfiguratorTests/MasterInstallerConfiguratorTests/ConfigurationModelTests.cs#L228)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6)_

**Comment by papeh** [comment]
Reviewed 11 of 12 files at r2, 1 of 1 files at r4.
Review status: 19 of 20 files reviewed at latest revision, 7 unresolved discussions.

---

*[Code and Projects/MasterInstallerConfigurator/ConfigurationWizard.cs, line 208 at r2](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-KCH9pDj3Up_QqRusCYU:-KCH9pDj3Up_QqRusCYV:bfpydmc) ([raw file](https://github.com/sillsdev/masterinstaller/blob/b60ec520082a95a1acb932ab2ecb04050458b1fc/Code and Projects/MasterInstallerConfigurator/ConfigurationWizard.cs#L208)):*
> ```Smalltalk
> 			{
> 				_vsBinPath.Text = value;
> 			}
> ```

these could be 1-line formatted like the rest

---

*[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 59 at r4](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-Kv7lBYLzHskiBCzpiES:-Kv7lBYLzHskiBCzpiET:b-pphucp) ([raw file](https://github.com/sillsdev/masterinstaller/blob/b2bf25118e2449b0e9c4b5cc5f5c2e25f5e330df/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L59)):*
> ```Smalltalk
> 				{
> 					FileName = Path.Combine(view.VSIncludePath, "..", "bin", "rc.exe"),
> 					Arguments = string.Format("/I \"{0}\" /I \"{1}\" /I \"{2}\" /i\"{3}\" /fo\"{4}\" \"{5}\"", Settings.Default.VSIncludePath,
> ```

is the little "i" intentional?

---

*[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 65 at r4](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-Kv7lN3KD6a4hlhH2hcv:-Kv7lN3KD6a4hlhH2hcw:b6rugcm) ([raw file](https://github.com/sillsdev/masterinstaller/blob/b2bf25118e2449b0e9c4b5cc5f5c2e25f5e330df/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L65)):*
> ```Smalltalk
> 					UseShellExecute = true,
> 					// do not start process in new window
> 					CreateNoWindow = false,
> ```

how hard would it be to rename this to `CreateNewWindow`?

---

*[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 71 at r4](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-Kv7l_56zFdCk0leqK47:-Kv7l_56zFdCk0leqK48:b-vpho1m) ([raw file](https://github.com/sillsdev/masterinstaller/blob/b2bf25118e2449b0e9c4b5cc5f5c2e25f5e330df/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L71)):*
> ```Smalltalk
> 			if (compilerProcess.Start())
> 			{
> 				compilerProcess.WaitForExit(2 * 60 * 1000);// wait for 2 minutes
> ```

2 mins in millis should go in a constant.

---

*[Utils/CompileXmlMasterInstaller.js, line 130 at r2](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6#-Kv3C9kKiGag9lr8MZmL:-Kv3C9kKiGag9lr8MZmM:b-nsdq6j) ([raw file](https://github.com/sillsdev/masterinstaller/blob/b60ec520082a95a1acb932ab2ecb04050458b1fc/Utils/CompileXmlMasterInstaller.js#L130)):*
> ```JavaScript
> 	// tso.Write(xslProc.output);
> 	// tso.Close();
> // }
> ```

don't forget to remove this commented code in your next PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6)*

**Comment by papeh** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/masterinstaller/6)*

**Comment by jasonleenaylor** [comment]
Cleaning house, this repo is no longer relevant.

**Pull request closed without merging**
