### PR TITLE
Implement much of the ConfigProducts functionality

### PR DESCRIPTION
**Pull request by jasonleenaylor**
- Modify model to add missing pieces used in ConfigProducts
- Generate variables for the Product structs
- Address minor review comment

[Review on Reviewable](https://reviewable.io/reviews/sillsdev/masterinstaller/5)

### CODE REVIEW

**Comment by papeh** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

<sup>**[Code and Projects/ConfigDisks.xsl, line 0 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3FmJnyY5GWv0jYwyvZ)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/405bbb332171fd0c4604dcb1746f245dd8608077/Code and Projects/ConfigDisks.xsl#L0)):</sup>
:smiley_cat:



---

<sup>**[Code and Projects/ConfigProducts.xsl, line 14 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3Fu8hPLa7LqBjryrV5)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/38dfa6fbb391342c28d3f34f5fc1265ca50f6b39/Code and Projects/ConfigProducts.xsl#L14)):</sup>
the warning should remain until the entire file is gone



---

<sup>**[Code and Projects/MasterInstallerConfigurator/ConfigurationModel.cs, line 116 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3GB5bd8DYkVQ03L0uv)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/405bbb332171fd0c4604dcb1746f245dd8608077/Code and Projects/MasterInstallerConfigurator/ConfigurationModel.cs#L116)):</sup>
blank line moved



---

<sup>**[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 82 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3GBxyRY5bEg5zC5Qbb)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/405bbb332171fd0c4604dcb1746f245dd8608077/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L82)):</sup>
Where is this `{` closed? (and three times above)



---

<sup>**[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 153 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3GQr5Y7wb_hkEPGuSc)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/405bbb332171fd0c4604dcb1746f245dd8608077/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L153)):</sup>
A number of inconsistencies in  the following GenerateProductSomethingVariable methods:
- bool and int types are missing `//` before comments
- A null Path variable results in a true `null`, but other stringy types (Function and String) result in the string `"NULL"` (generated with different but equivalent code)
- It would be nice to have stringy types (Path, Function, String) adjacent, and perhaps even have Path and Function call String, for clarity.
  

---

<sup>**[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 159 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3GHUjaX5Xxkte2UEjW)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/405bbb332171fd0c4604dcb1746f245dd8608077/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L159)):</sup>
How about `@"\", @"\\"`



---

<sup>**[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 159 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3GHfG_isjXlN_J0KAP)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/405bbb332171fd0c4604dcb1746f245dd8608077/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L159)):</sup>
It was nice to see the xsl go, but we're still generating C++ with macros.  Baby steps. :footprints: 



---

<sup>**[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 169 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3GIslV3Fcu7TUddHIg)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/405bbb332171fd0c4604dcb1746f245dd8608077/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L169)):</sup>
would be better to have both `GenerateProductIntVariable` overloads adjacent.



---

<sup>**[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 191 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3GNmc8GdXzgfXqcxon)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/405bbb332171fd0c4604dcb1746f245dd8608077/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L191)):</sup>
If null, this will generate
`_T("NULL")`
not
`T(NULL)` or `NULL`
Is this intentional?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5)

**Comment by jasonleenaylor** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 82 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3GBxyRY5bEg5zC5Qbb)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/405bbb332171fd0c4604dcb1746f245dd8608077/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L82)):</sup>
This one isn't closed because I haven't reached the end yet.  ;)



---

<sup>**[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 169 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3GIslV3Fcu7TUddHIg)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/405bbb332171fd0c4604dcb1746f245dd8608077/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L169)):</sup>
Done.



---

<sup>**[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 191 [r1]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3GNmc8GdXzgfXqcxon)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/405bbb332171fd0c4604dcb1746f245dd8608077/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L191)):</sup>
Done.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5)

**Comment by papeh** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 135 [r2]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3H5N2WoxVs_ySKS93S)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/34d526996d2bed24c8ee3e1480eabc6e7d84381d/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L135)):</sup>
If it's obsolete, how soon can we remove it?



---

<sup>**[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 202 [r2]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3H6D2yrpyHEEElPdYJ)** ([raw file](https://github.com/sillsdev/masterinstaller/blob/34d526996d2bed24c8ee3e1480eabc6e7d84381d/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L202)):</sup>
`stringValue` may be better than `pathValue`



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5)

**Comment by jasonleenaylor** [comment]
Review status: 5 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs, line 202 [r2]](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5#-K3H6D2yrpyHEEElPdYJ:-K3_kGpOlxMMZLbe0jM9:-499146009) ([raw file](https://github.com/sillsdev/masterinstaller/blob/34d526996d2bed24c8ee3e1480eabc6e7d84381d/Code and Projects/MasterInstallerConfigurator/MasterInstallerCompiler.cs#L202)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/masterinstaller/5)_

**Pull request merged**
